### PR TITLE
Update to tyxml 4

### PR DESCRIPTION
**Pull request by smondet**
The function `a_autocomplete` now takes a boolean.

All the other changes are

```vimL
:%s/Html5/Html/gc
```

---
This change is [Reviewable](https://reviewable.io/reviews/hammerlab/ketrew/468)

### CODE REVIEW

**Comment by ihodes** [comment]
LGTM! Does this mean we're OCaml 4.03 ready?

**Comment by smondet** [comment]
@ihodes I'm trying now :)
If it works I'll add to the Travis config.

**Comment by ihodes** [comment]
Awesome!

**Comment by smondet** [comment]
Module this issue: https://github.com/mirleft/ocaml-nocrypto/issues/104
(i.e. we need `opam pin add oasis 0.4.6`), `ketrew` built successfully on `4.03.0+flambda`!

**Comment by smondet** [comment]
I added the 4.03.0 to the Travis build → **may have to `push --force`.**

**Comment by smondet** [comment]
screenshot 2016-09-08 10 40 15

**Pull request merged**
