### PR TITLE
More Ssh hacks for #212

### PR DESCRIPTION
**Pull request by smondet**
This is all towards #212.

It mostly deals with the adding of “named hosts” which are dynamically resolved during execution, and can be created form the WebUI.

I meant to put these 2 in a separate PR but with some git mess-up and recovery they ended-up in-between the rest of the PR:

- https://github.com/hammerlab/ketrew/commit/b9137b6923c724684d350528ee2cfce74a45a55b displays whether the ASKPASS program is waiting on input form the “user”
- https://github.com/hammerlab/ketrew/commit/cf4873d8175fc3abe62c73aa3e354bb61b1dd586 is just adding an MLI file

[Review on Reviewable](https://reviewable.io/reviews/hammerlab/ketrew/250)

### CODE REVIEW

**Comment by smondet** [comment]
To do a “full loop test:”

- start server, go to WebUI `Processes` tab
- add an SSH connection, named `TheName`, make it work (I use vagrant boxes, with `vagrant@127.0.0.1:2222` which asks me to enter a password in the UI)
- try it with `kdclient submit --daemonize=named://TheName/tmp/KT,"du -sh" -w

**Comment by rleonid** [comment]
How do I start the server:
```bash
yellowhammer:ketrew$ git status .
On branch ssh-hacks-i212
Your branch is up-to-date with 'origin/ssh-hacks-i212'.
Untracked files:
  (use "git add <file>..." to include in what will be committed)

	.merlin
	.ocamlinit

nothing added to commit but untracked files present (use "git add" to track)
yellowhammer:ketrew$ git pull origin ssh-hacks-i212 
From https://github.com/hammerlab/ketrew
 * branch            ssh-hacks-i212 -> FETCH_HEAD
Already up-to-date.
yellowhammer:ketrew$ omake
*** omake: reading OMakefiles
Go!
Not using Bisect:  
LIB ketrew_pure MODULES: internal_pervasives path host target program protocol reactive monitored_script metadata
internal_pervasives.cmx path.cmx host.cmx target.cmx program.cmx protocol.cmx reactive.cmx monitored_script.cmx metadata.cmx
internal_pervasives.cmi path.cmi host.cmi target.cmi program.cmi protocol.cmi reactive.cmi monitored_script.cmi metadata.cmi
APP ketrew-client-joo MODULES: reactive_html5 webapp pvem_js pvem_js target_page local_cache target_table target_page local_cache processes_ui target_table single_client processes_ui single_client reactive_html5 protocol_client protocol_client 
APP ketrew-client-joo local_deps: ../pure/ketrew_pure.cmi          ../pure/ketrew_pure.cmo
LIB ketrew MODULES: long_running_utilities pbs lsf eDSL yarn error engine server plugin client unix_io host_io logging document explorer daemonize interaction unix_process command_line long_running configuration eval_condition process_holder authentication persistent_data client_html
long_running_utilities.cmx pbs.cmx lsf.cmx eDSL.cmx yarn.cmx error.cmx engine.cmx server.cmx plugin.cmx client.cmx unix_io.cmx host_io.cmx logging.cmx document.cmx explorer.cmx daemonize.cmx interaction.cmx unix_process.cmx command_line.cmx long_running.cmx configuration.cmx eval_condition.cmx process_holder.cmx authentication.cmx persistent_data.cmx client_html.cmx
long_running_utilities.cmi pbs.cmi lsf.cmi eDSL.cmi yarn.cmi error.cmi engine.cmi server.cmi plugin.cmi client.cmi unix_io.cmi host_io.cmi logging.cmi document.cmi explorer.cmi daemonize.cmi interaction.cmi unix_process.cmi command_line.cmi long_running.cmi configuration.cmi eval_condition.cmi process_holder.cmi authentication.cmi persistent_data.cmi client_html.cmi
APP ketrew MODULES: cli_main 
APP ketrew local_deps: ../pure/ketrew_pure.cmi ../lib/ketrew.cmi          ../pure/ketrew_pure.o ../lib/ketrew.o
LIB dummy_plugin_test_lib MODULES: dummy_plugin 
dummy_plugin.cmx
dummy_plugin.cmi
*** omake: finished reading OMakefiles (0.04 sec)
- build . _build/style.css                                                                                                                                                                                                                                                                
+ Shell.echo("'Building _build/style.css'")
Building _build/style.css
*** omake: done (26.34 sec, 1/81 scans, 127/187 rules, 272/759 digests)                                                                                                                                                                                                                   
yellowhammer:ketrew$ ls
CONTRIBUTING.md			OMakeroot.omc			_doc				gen				ketrew-integration-test		ketrew-workflow-examples-test	setup.ml
DIRNAME				README.md			_oasis				ketrew				ketrew-preconfigured-test	opam				src
LICENSE				_apidoc				_report_dir			ketrew-client-joo		ketrew-test			setup.data			tools
OMakeroot			_build				_test_env			ketrew-dummy-plugin-user	ketrew-workflow-examples	setup.log
yellowhammer:ketrew$ omake test-env
*** omake: reading OMakefiles
Go!
Not using Bisect:  
LIB ketrew_pure MODULES: internal_pervasives path host target program protocol reactive monitored_script metadata
internal_pervasives.cmx path.cmx host.cmx target.cmx program.cmx protocol.cmx reactive.cmx monitored_script.cmx metadata.cmx
internal_pervasives.cmi path.cmi host.cmi target.cmi program.cmi protocol.cmi reactive.cmi monitored_script.cmi metadata.cmi
APP ketrew-client-joo MODULES: reactive_html5 webapp pvem_js pvem_js target_page local_cache target_table target_page local_cache processes_ui target_table single_client processes_ui single_client reactive_html5 protocol_client protocol_client 
APP ketrew-client-joo local_deps: ../pure/ketrew_pure.cmi          ../pure/ketrew_pure.cmo
LIB ketrew MODULES: long_running_utilities pbs lsf eDSL yarn error engine server plugin client unix_io host_io logging document explorer daemonize interaction unix_process command_line long_running configuration eval_condition process_holder authentication persistent_data client_html
long_running_utilities.cmx pbs.cmx lsf.cmx eDSL.cmx yarn.cmx error.cmx engine.cmx server.cmx plugin.cmx client.cmx unix_io.cmx host_io.cmx logging.cmx document.cmx explorer.cmx daemonize.cmx interaction.cmx unix_process.cmx command_line.cmx long_running.cmx configuration.cmx eval_condition.cmx process_holder.cmx authentication.cmx persistent_data.cmx client_html.cmx
long_running_utilities.cmi pbs.cmi lsf.cmi eDSL.cmi yarn.cmi error.cmi engine.cmi server.cmi plugin.cmi client.cmi unix_io.cmi host_io.cmi logging.cmi document.cmi explorer.cmi daemonize.cmi interaction.cmi unix_process.cmi command_line.cmi long_running.cmi configuration.cmi eval_condition.cmi process_holder.cmi authentication.cmi persistent_data.cmi client_html.cmi
APP ketrew MODULES: cli_main 
APP ketrew local_deps: ../pure/ketrew_pure.cmi ../lib/ketrew.cmi          ../pure/ketrew_pure.o ../lib/ketrew.o
LIB dummy_plugin_test_lib MODULES: dummy_plugin 
dummy_plugin.cmx
dummy_plugin.cmi
*** omake: finished reading OMakefiles (0.04 sec)
- build . <test-env>
+ Shell.echo(Using package lwt.react as findlin-plugin Creating cert-key pair: _test_env/test-cert.pem, _test_env/test-key.pem Creating _test_env/configuration.ml Creating _test_env/test-authorized-tokens Creating _test_env/env.env)
Using package lwt.react as findlin-plugin Creating cert-key pair: _test_env/test-cert.pem, _test_env/test-key.pem Creating _test_env/configuration.ml Creating _test_env/test-authorized-tokens Creating _test_env/env.env
*** omake: done (0.41 sec, 0/0 scans, 1/1 rules, 0/72 digests)
yellowhammer:ketrew$ source _test_env/
client-config-file.toml      configuration.ml             env.env                      server-config-file.toml      standalone-config-file.toml  test-authorized-tokens       test-cert.pem                test-key.pem                 
yellowhammer:ketrew$ source _test_env/env.env 
yellowhammer:ketrew$ kdserver start-server -P server
[ketrew: debug] Going to load: [ ]
[ketrew: debug] 
    Going to load: [
        "/Users/.../.opam/4.02.3/lib/lwt/lwt-react.cmxs"
    ]
[ketrew: debug] Loading: "/Users/.../.opam/4.02.3/lib/lwt/lwt-react.cmxs"
[ketrew: debug] Loading: "/Users/.../Documents/code/hammer/ketrew/_build/src/test/dummy-plugin/dummy_plugin_test_lib.cmxs"
ketrew: internal error, uncaught exception:
        Dynlink.Error(_)
        Raised at file "dynlink.mlopt", line 52, characters 42-70
        Called from file "dynlink.mlopt", line 182, characters 32-55
        Called from file "list.ml", line 73, characters 12-15
        Called from file "configuration.ml", line 468, characters 4-47
yellowhammer:ketrew$ kdclient start-server -P server
[ketrew: debug] Going to load: [ ]
[ketrew: debug] 
    Going to load: [
        "/Users/.../.opam/4.02.3/lib/lwt/lwt-react.cmxs"
    ]
[ketrew: debug] Loading: "/Users/.../.opam/4.02.3/lib/lwt/lwt-react.cmxs"
[ketrew: debug] Loading: "/Users/.../Documents/code/hammer/ketrew/_build/src/test/dummy-plugin/dummy_plugin_test_lib.cmxs"
ketrew: internal error, uncaught exception:
        Dynlink.Error(_)
        Raised at file "dynlink.mlopt", line 52, characters 42-70
        Called from file "dynlink.mlopt", line 182, characters 32-55
        Called from file "list.ml", line 73, characters 12-15
        Called from file "configuration.ml", line 468, characters 4-47
```

**Comment by smondet** [comment]
`omake test-env` assumes `omake build-all`

**Comment by rleonid** [comment]
Ok, got running and a vagrant box too. But, unfortunately, nothing happened.
http://f.cl.ly/items/0Z1R2u0v0l2S3w042D2z/Screen%20Recording%202015-11-10%20at%2005.21%20PM.gif

**Comment by smondet** [comment]
Ah yes, the UI improvements are for a later PR. For now you need to click on "Update List" to refresh the list, it will show up.

**Comment by rleonid** [comment]
@smondet I've looked over the PR and nothing seems out of the ordinary.

As discussed on slack, I don't think that this functionality is worth the code. As currently implemented and documented, it is not easy to understand how that functionality is achieved. In order to properly review this PR, I would need to fully understand most of the `ketrew` library, something I currently do not. Consequently, I cannot give you a thorough review.

**Pull request merged**
