### PR TITLE
Yarn application name sanitization

### PR DESCRIPTION
**Pull request by smondet**
This change is [Reviewable](https://reviewable.io/reviews/hammerlab/ketrew/415)

### CODE REVIEW

**Comment by ihodes** [comment]
Can't we do this at the Hamkepi/Machine level?

**Comment by ihodes** [comment]
Can we do this at the Hamkepi/Machine level?

**Comment by smondet** [comment]
@ihodes it's a global fix to make sure users don't get hurt *by default* ;)

**Comment by ihodes** [comment]
Makes sense, LGTM!

**Pull request merged**
