### PR TITLE
Bisect code coverage

### PR DESCRIPTION
**Pull request by rleonid**
Addressing https://github.com/hammerlab/ketrew/issues/59

[Review on Reviewable](https://reviewable.io/reviews/hammerlab/ketrew/112)

### CODE REVIEW

**Comment by smondet** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/ketrew/112)







---

<sup>**[myocamlbuild.ml, line 4 \[r1\]](https://reviewable.io:443/reviews/hammerlab/ketrew/112#-JjQuZpb-3x9cMbYgBp1)** ([raw file](https://github.com/hammerlab/ketrew/blob/7f621c3c79a11ff051e15f4750dcd9218cf761ea/myocamlbuild.ml#L4)):</sup>
Can you add a small documentation/comment about this file?

---

<sup>**[src/doc/Developer_Documentation.md, line 152 \[r1\]](https://reviewable.io:443/reviews/hammerlab/ketrew/112#-JjQujKEl5O6dw4NWiSS)** ([raw file](https://github.com/hammerlab/ketrew/blob/7f621c3c79a11ff051e15f4750dcd9218cf761ea/src/doc/Developer_Documentation.md#L152)):</sup>
Could you wrap the text at 80 chars (to be consistent with all the rest of the Markdown we have)?

---

**Comment by smondet** [comment]
Also, the branch is pretty far from `master`, did you try to merge/rebase it?

screenshot 2015-03-02 14 33 11

**Comment by rleonid** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/ketrew/112)



---

Done!

---

<sup>**[myocamlbuild.ml, line 4 \[r1\]](https://reviewable.io:443/reviews/hammerlab/ketrew/112#-JjQuZpb-3x9cMbYgBp1)** ([raw file](https://github.com/hammerlab/ketrew/blob/7f621c3c79a11ff051e15f4750dcd9218cf761ea/myocamlbuild.ml#L4)):</sup>
Done.

---

**Comment by smondet** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/ketrew/112)

Reviewed files:
- .gitignore @ r1
- Makefile @ r1
- myocamlbuild.ml @ r2
- src/atd/target_v0.atd @ r2
- src/doc/Developer_Documentation.md @ r2
- src/lib/pure/ketrew_edsl.ml @ r1
- src/lib/pure/ketrew_target.ml @ r2
- src/lib/pure/ketrew_target.mli @ r2
- src/test/main.ml @ r2
- tools/_oasis.in @ r1





---

**Comment by rleonid** [comment]
@smondet do you want me to make these
```
eval `./tools/cr.sh start-session`  # creates a directory _bisect_YYYYMMDD_HHMMSS, set BISECT_FILE=
# ... run stuff ... 
eval `./tools/cr.sh finish` # creates ./_bisect_YYYYMMDD_HHMMSS/report/  with all the files created, unset BISECT_FILE
```
changes for cr.sh  in this branch.

**Comment by smondet** [comment]
As you prefer, I can also merge and keep this for later ?

**Pull request merged**
