### PR TITLE
Unrestify the HTTP API

### PR DESCRIPTION
**Pull request by smondet**
Now every up-message is a `POST` to the `/api` service. This makes it much more readable (everything is in `protocol_v0.atd`) and portable (could easily make it work with another transport layer, like SSH or plain TCP).

[Review on Reviewable](https://reviewable.io/reviews/hammerlab/ketrew/122)

### CODE REVIEW

**Comment by rleonid** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/ketrew/122)

Reviewed files:
- src/atd/protocol_v0.atd @ r1
- src/atd/versioned.atd @ r1
- src/doc/The_HTTP_API.md @ r1
- src/lib/ketrew_client.ml @ r1
- src/lib/ketrew_command_line.ml @ r1
- src/lib/ketrew_server.ml @ r1
- src/lib/pure/ketrew_protocol.ml @ r1
- src/lib/pure/ketrew_protocol.mli @ r1

---

I can't say that I fully understand the motivation for this change, as I haven't grokked the code. Seems like some algebraic refactoring. So fine with me.

---

<sup>**[src/atd/protocol_v0.atd, line 30 \[r1\]](https://reviewable.io:443/reviews/hammerlab/ketrew/122#-Jl7n6GQsTfmWLVu53yV)** ([raw file](https://github.com/hammerlab/ketrew/blob/0948861841138de7d721cb1177c68cf0fe6414e3/src/atd/protocol_v0.atd#L30)):</sup>
What about renaming these to
`up` -> `to_server`
`down` -> `to_client`

---

<sup>**[src/atd/protocol_v0.atd, line 37 \[r1\]](https://reviewable.io:443/reviews/hammerlab/ketrew/122#-Jl7mJWc71O347ZtElMx)** ([raw file](https://github.com/hammerlab/ketrew/blob/0948861841138de7d721cb1177c68cf0fe6414e3/src/atd/protocol_v0.atd#L37)):</sup>
What do you think of aligning the comments?
The code below is adjusted for looking pretty in the preview
```
  | Get_targets of string list           (* List of Ids, empty means “all” *)
  | Get_available_queries of string      (* Id of the target *)
  | Call_query of (string * string)      (* target-id × query-name *)
  | Submit_targets of target_v0 list
  | Kill_targets of string list          (* List of Ids *)
  | Restart_targets of string list       (* List of Ids *)
```

---

**Comment by smondet** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/ketrew/122)



---


The motivation is to be able to add messages to the protocol much faster, thanks to more type safety (the `/<service>` were just strings, while the `{up,down}_message` types provide exhaustiveness checking) and “locality” (the whole protocol definition is in one ATD file instead of 3).

The good side effect is that it makes it much easier, in the future, to add another “authenticated transport” layer (like SSH).

---

<sup>**[src/atd/protocol_v0.atd, line 30 \[r1\]](https://reviewable.io:443/reviews/hammerlab/ketrew/122#-Jl7n6GQsTfmWLVu53yV)** ([raw file](https://github.com/hammerlab/ketrew/blob/0948861841138de7d721cb1177c68cf0fe6414e3/src/atd/protocol_v0.atd#L30)):</sup>
I think “up” and “down” are pretty common in the literature.

---

<sup>**[src/atd/protocol_v0.atd, line 37 \[r1\]](https://reviewable.io:443/reviews/hammerlab/ketrew/122#-Jl7mJWc71O347ZtElMx)** ([raw file](https://github.com/hammerlab/ketrew/blob/0948861841138de7d721cb1177c68cf0fe6414e3/src/atd/protocol_v0.atd#L37)):</sup>
One of the problems with code alignment is consistency :)
Would you align the `of` keywords also there?

What do you do when one of those comments goes after the 80th column?

---

**Comment by rleonid** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/ketrew/122)







---

<sup>**[src/atd/protocol_v0.atd, line 37 \[r1\]](https://reviewable.io:443/reviews/hammerlab/ketrew/122#-Jl7mJWc71O347ZtElMx)** ([raw file](https://github.com/hammerlab/ketrew/blob/0948861841138de7d721cb1177c68cf0fe6414e3/src/atd/protocol_v0.atd#L37)):</sup>
You don't need to necessarily align the `of`, I just think the comments that explain the parameters look nicer aligned. If it goes longer than 80 then make it shorter or reconsider your original declaration. For example, we can compress the logic a bit to:

```
type targets = string list (* List of Ids, empty means “all” *)

type up_message = [
  | Get of targets 
  | Get_available_queries of string (* Id of the target *)                                                                                  
  | Call_query of (string * string) (* target-id × query-name *)                                                                            
  | Submit_targets of target_v0 list                                                                                                        
  | Kill of targets 
  | Restart of targets 
] 
```

assuming that an empty list would operate as "all" for `Kill` and `Restart` , but that's another to to specify and make the `targets` type richer.

---

**Comment by smondet** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/ketrew/122)







---

<sup>**[src/atd/protocol_v0.atd, line 37 \[r1\]](https://reviewable.io:443/reviews/hammerlab/ketrew/122#-Jl7mJWc71O347ZtElMx)** ([raw file](https://github.com/hammerlab/ketrew/blob/0948861841138de7d721cb1177c68cf0fe6414e3/src/atd/protocol_v0.atd#L37)):</sup>

Overall for the vertical alignment I prefer keeping the discussion there:
https://github.com/hammerlab/style-guides/issues/2

OK with that?

---

**Comment by rleonid** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/ketrew/122)







---

<sup>**[src/atd/protocol_v0.atd, line 37 \[r1\]](https://reviewable.io:443/reviews/hammerlab/ketrew/122#-Jl7mJWc71O347ZtElMx)** ([raw file](https://github.com/hammerlab/ketrew/blob/0948861841138de7d721cb1177c68cf0fe6414e3/src/atd/protocol_v0.atd#L37)):</sup>
Sure, what do you think about having a `targets` type?

---

**Comment by smondet** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/ketrew/122)







---

<sup>**[src/atd/protocol_v0.atd, line 37 \[r1\]](https://reviewable.io:443/reviews/hammerlab/ketrew/122#-Jl7mJWc71O347ZtElMx)** ([raw file](https://github.com/hammerlab/ketrew/blob/0948861841138de7d721cb1177c68cf0fe6414e3/src/atd/protocol_v0.atd#L37)):</sup>

In that case since "empty" means something different, I would not add confusion.

Moreover, with ATD, every new type adds a little cost (new module), I don't think it is worth it.

I would not call it `targets` but `target_ids`.

---

**Pull request merged**
