### PR TITLE
Simplify the build to use bisect_ppx.

### PR DESCRIPTION
**Pull request by rleonid**
Goodbye `Camlp4` and `Bisect`. Hello `bisect_ppx`!

[Review on Reviewable](https://reviewable.io/reviews/hammerlab/ketrew/179)

### CODE REVIEW

**Comment by hammer** [comment]
:clap:

**Comment by smondet** [comment]
I think using `bisect_ppx` should work without any `myocamlbuild.ml` at all.

I prefer adding the logic to `tools/please.ml`, I will try later.

**Comment by rleonid** [comment]
We're only using `myocamlbuild.ml` for the coverage integration with `Oasis`. Looking back on it, it is remarkably hacky.

The current build logic looks something like this

```
make -> please.ml -> Oasis  [ configuration]
  \---> Oasis     -> ocamlbuild [ build]
  \---> tools     -> [tests/doc].
```
Since `ocamlbuild` forces us to write code in `myocamlbuild.ml` anyway I agree that it would be easier to just write `OCaml` in one place, and if `please.ml` is the place that's fine with me. But if we do that, I would be in favor of getting rid of `Oasis` and just having `please.ml` call `ocamlbuild` directly. To keep the build process focused in a smaller number of files.

**Comment by smondet** [comment]
My point is that we don't need a `myocamlbuild.ml` file at all.

The oasis-generated one should be enough (and then we can avoid having oasis modifying a file tracked by `git`).

**Comment by rleonid** [comment]
Fair enough, I'd be interested to see how you get `Oasis` to get coverage.

**Pull request closed without merging**
