### PR TITLE
Use failure_triggers uniformly.

### PR DESCRIPTION
**Pull request by rleonid**
@arahuja Did the heavy work of proposing a name. But this addresses #172 and does a good job in my mind.

[Review on Reviewable](https://reviewable.io/reviews/hammerlab/ketrew/180)

### CODE REVIEW

**Comment by smondet** [comment]
But then `dependencies` is a plural noun while the other two are 3rd person verbs, should we uniformize that also?

**Comment by smondet** [comment]
(note: The travis error is in `biokepi` this PR builds fine)

**Comment by rleonid** [comment]
> But then dependencies is a plural noun while the other two are 3rd person verbs, should we uniformize that also?

They operate as plural nouns so it's fine.

**Comment by smondet** [comment]
Sorry for being picky, but “trigger” as a noun does not mean "thing triggered" it's the "thing that triggers" hence the opposite of what we want
http://www.merriam-webster.com/dictionary/trigger

**Comment by rleonid** [comment]
No worries, that's true. I guess when I read it, it seems intuitive that it refers to the success/failure of the target, and "trigger" is used in an operative sense that something will happen.

Two other idea's:
1. Use 'delegate' instead of 'trigger'
2. How about using "on_success" or "on_failure" for these lists?

**Comment by smondet** [comment]
of `dependencies` → `depends` or `depends_on` ?

**Comment by rleonid** [comment]
How about 'both'
`dependencies` -> `depends_on`
_and_
`success_trigger` -> `on_success`
`failure_trigger` -> `on_failure`

**Comment by smondet** [comment]
But then we're again with a mix of nouns and verbs

I think I like:

- `depends_on`
- `success_triggers`
- `failure_triggers`

**Comment by arahuja** [comment]
My vote: `depends_on`, `on_success`, `on_failure`

-1 on `success_trigger` at least

**Comment by hammer** [comment]
Scope creep alert: why do we use the rigid communication channel of `on_success` and `on_failure` rather than allowing targets to communicate and respond to arbitrary states? It's like having special syntax for pattern matching on booleans (callback to earlier "if/then" vs. "match" debates)!

**Comment by smondet** [comment]
@hammer Interesting

The thing is that there are many actual states.

Something like this:

```ocaml
...
activate:( Target.State.t -> target list ) list ->
...
```

is problematic because it makes the target non-serializable (closure).

So it has to be

```ocaml
activate:(some_static_representation_of_matching_a_state * target list) list ->
```
 
with the current implementation being equivalent to:

```ocaml
type some_static_representation_of_matching_a_state = [
  | `Failure
  | `Success
]
```

I kinda like it, it's more future-proof (adding cases to that variant can remain backwards compatible).

I don't know which one is more readable/understandable.

@rleonid , @arahuja ?


The whole thing can then also be extended also on the "Action" side:

```ocaml
type some_action = [
   | `Activate of target list
   | `Kill of target list
   | `List of some_action list
...
react:(some_static_representation_of_matching_a_state * some_action) list ->
...
```

**Comment by hammer** [comment]
I'll defer to the designer and users, though I've found open vocabularies to be useful for workflow systems I've built and used in the past.

**Comment by rleonid** [comment]
I am of two minds on this. On the one hand, in the interest of keeping it simple and making adaption easier `depends_on`, `on_success`, `on_failure` is the way.

On the other hand Jeff has a good point, allowing a user to associate custom status checks with a target and corresponding other targets based on those states would be powerful. Could we implement that logic via a first class module, like the plugins?

Regardless, my vote is for the former at the beginning. I don't know if we've yet run in to a use case for the latter.

**Comment by smondet** [comment]
Yes but I'd like to get as many API breaking changes as possible in the next version.

Also, they're are not exclusive, we can have `depends_on`, `on_success`, and `on_failure` as special shortcuts to `react`.

**Comment by rleonid** [comment]
Staying back on track to the uniform naming scheme, no more `triggers` just `on_success` and `on_failure`. I also removed references to `fallbacks`, although in hindsight, I like that name as much as `failure`.

**Comment by rleonid** [comment]
And now `dependencies` -> `depends_on`

**Comment by smondet** [comment]
In https://github.com/hammerlab/ketrew/pull/182 I used `on_success_activate` and `on_failure_activate` to be more future-friendly (future could be `on_success_kill` or more). What do you think?

**Comment by rleonid** [comment]
Do you mean have separate `on_success_activate` arguments to constructing `user_targets` ?

I think that a better way to go would be to avoid putting in more specification into target construction and to allow functions such as `on_success` that take two `targets`. This way the dependencies between `targets` can be about specifying different types of *edges*, while arguments about `targets` would be about configuring the *nodes*.

**Comment by smondet** [comment]
It is already about configuring edges, the question is to name the argument `on_success` or `on_success_activate`. I prefer the longest/most explicit/ future-friendly.

If you want `on_success` (or any of those) to be a separate function that means having a global variable that records those edges or making targets mutable; which I think is too dirty, and can make the EDSL difficult to reason about.

**Comment by rleonid** [comment]
But there is already a global state, namely the script itself. I think that most developers would find the graph analogy easy to reason about. Whether the logic of the relationship between two targets is stored inside of the targets or elsewhere can be kept hidden from the user.

**Comment by smondet** [comment]
No, in *norma*l usage of the EDSL, the whole workflow is linked inside the “root” target (a.k.a. the common ancestor) which is not a global value; usually the result of a function that creates the workflow.

I see the value in separating the edges from the nodes, but it means that we would require the user to register them in some "workflow" value, and then we'd have to deal with dangling pointers, duplicates, and cycles. And the user's functions would have to pass around that workflow value; or make it global.

**Comment by smondet** [comment]
This has been applied manually.

**Pull request closed without merging**
